name: AutoTask
on:
  push:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download bin
        run: |
          wget https://github.com/XiaoMengXinX/Fuck163MusicTasks/releases/download/v2.1.8/Fuck163MusicTasks_linux_amd64
          chmod 777 ./Fuck163MusicTasks_linux_amd64
      - name: Export Config
        env:
          CONFIG: ${{ secrets.CONFIG }}
          # Just a simple hiding example, you can hide your nickname, music id and other things
          NICKNAME: ${{ secrets.NICKNAME }}
        run: |
          # Hiding
          echo "::add-mask::$NICKNAME"
          echo "$CONFIG" > config.json
      - name: Run Fuck163MusicTasks
        run: |
          ./Fuck163MusicTasks_linux_amd64
